version: "3"
services:
    client-data:
        image: node:14-alpine
        container_name: client-data
        working_dir: /usr/app
        command: /bin/sh -c "npm install && npm run start"
        ports:
            - 3000:3000
        volumes: 
            - ./client-data-provider:/usr/app
            - /usr/app/node_modules
    item-data:
        image: node:14-alpine
        container_name: item-data
        working_dir: /usr/app
        command: /bin/sh -c "npm install && npm run start"
        ports:
            - 3001:3000
        volumes: 
            - ./item-data-provider:/usr/app
            - /usr/app/node_modules
    notify-client:
        image: node:14-alpine
        container_name: notify-client
        working_dir: /usr/app
        command: /bin/sh -c "npm install && npm run start"
        ports:
            - 3002:3000
        volumes: 
            - ./notify-client-consumer:/usr/app
            - /usr/app/node_modules
        environment: 
            - CLIENT_DATA="client-data:3000"
    costumer-purchase:
        image: node:14-alpine
        container_name: costumer-purchase
        working_dir: /usr/app
        command: /bin/sh -c "npm install && npm run start"
        ports:
            - 3003:3000
        volumes: 
            - ./costumer-purchase-consumer:/usr/app
            - /usr/app/node_modules
        environment: 
            - CLIENT_DATA="client-data:3000"
            - ITEM_DATA="item-data:3000"
    pact-broker:
        image: pactfoundation/pact-broker
        container_name: pact-broker
        ports:
            - 9292:9292
        depends_on:
            - pact-postgres
        environment:
            PACT_BROKER_PORT: '9292'
            PACT_BROKER_DATABASE_URL: "postgres://postgres:password@pact-postgres/postgres"
            PACT_BROKER_LOG_LEVEL: INFO
            PACT_BROKER_SQL_LOG_LEVEL: DEBUG
            PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
            PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://pact-broker:9292'
    pact-postgres:
        image: postgres
        container_name: pact-postgres
        healthcheck:
          test: psql postgres --command "select 1" -U postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
